# .pre-commit-config.yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.0
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

# Use local Ruff installation from Poetry
default_language_version:
  python: python3.12  # Using Python 3.12
default_install_hook_types: [pre-commit, pre-push]
