version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./status_tiles:/app/status_tiles
      - ./tests:/app/tests
    environment:
      - DEBUG=1
      - LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"
    command: poetry run uvicorn status_tiles.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
